# General Jekyll Config
highlighter: rouge
url: https://www.dennisperrone.com
lsi: false
permalink: /:categories/:year/:month/:title/
plugins:
 - jekyll-feed
 - jekyll-seo-tag
title: Dennis' Thoughts on Tech and Cyber Security

include:
  - "_pages"
  - "_feeds"

exclude: [LICENSE, CNAME, README.md, .gitignore]


#title: Another tech blog

#description: > # this means to ignore newlines until "show_excerpts:"
#  A blog about personal and professional development and advancement within the Information Technology and Information Security space.
#show_excerpts: false # set to true to show excerpts on the homepage


